// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A content topic suggestion AI agent.
 *
 * - suggestContentTopics - A function that handles the content topic suggestion process.
 * - SuggestContentTopicsInput - The input type for the suggestContentTopics function.
 * - SuggestContentTopicsOutput - The return type for the suggestContentTopics function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestContentTopicsInputSchema = z.object({
  niche: z.string().describe('The content creator\'s niche or area of focus.'),
  audienceAnalysis: z.string().describe('An analysis of the target audience, including their interests and demographics.'),
  trendingTopics: z.string().describe('A list of trending topics in the creator\'s niche.'),
});
export type SuggestContentTopicsInput = z.infer<typeof SuggestContentTopicsInputSchema>;

const SuggestContentTopicsOutputSchema = z.object({
  topicSuggestions: z
    .array(z.string())
    .describe('A list of suggested content topics based on the input data.'),
});
export type SuggestContentTopicsOutput = z.infer<typeof SuggestContentTopicsOutputSchema>;

export async function suggestContentTopics(input: SuggestContentTopicsInput): Promise<SuggestContentTopicsOutput> {
  return suggestContentTopicsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestContentTopicsPrompt',
  input: {schema: SuggestContentTopicsInputSchema},
  output: {schema: SuggestContentTopicsOutputSchema},
  prompt: `You are a content creation expert. You will generate a list of content topics based on the provided niche, audience analysis, and trending topics.

Niche: {{{niche}}}
Audience Analysis: {{{audienceAnalysis}}}
Trending Topics: {{{trendingTopics}}}

Generate a list of engaging content topics that would appeal to the target audience and align with the creator\'s niche. The topics should be inspired by the trending topics provided. Return them as a list of strings.`,
});

const suggestContentTopicsFlow = ai.defineFlow(
  {
    name: 'suggestContentTopicsFlow',
    inputSchema: SuggestContentTopicsInputSchema,
    outputSchema: SuggestContentTopicsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
